### PR TITLE
Updates for espressif soc

### PR DESCRIPTION
**Pull request by microDev1**
I haven't actually tested the library on esp32c3 but it should probably work.

### CODE REVIEW

**Comment by ladyada** [comment]
hi, we'd definitely need it tested before merging since folks will ask for support!

**Comment by microDev1** [comment]
Force-pushed to fix formatting. I don't have a HUB75-style matrix to test this.

**Comment by microDev1** [comment]
Can we get this in without a test as that way more people can get a chance to test this and it will also allow me to include the `rgbmatrix` module for esp32c3 in CircuitPython, people can always open an issue if it doesn't work.

**Comment by ladyada** [comment]
oof - we really prefer not to, its confusing to merge in untested code. @UnexpectedMaker do you want to test the PR?

**Comment by UnexpectedMaker** [comment]
> oof - we really prefer not to, its confusing to merge in untested code. @UnexpectedMaker do you want to test the PR?

Sure, I’ll try to find some time to test this over the weekend.

**Comment by microDev1** [comment]
Now includes:
- support esp-idf v4.4
- add esp32c3 and esp32s3 support

**Review by jepler — APPROVED** [review]
I tested this on esp32-s2 (metro) only, and it works as before. I didn't test s3/c3.

**Pull request merged**
