### PR TITLE
Update for arduino esp32 3.0.0-rc1

### PR DESCRIPTION
**Pull request by jepler**
This is tested on the Adafruit Matrixportal S3. It's likely that further work is needed for other esp-family mcus.

### CODE REVIEW

**Comment by jepler** [comment]
too much to hope that it'd work on the first try...
```
Protomatter begin() status: 0
Refresh FPS = ~3759481730
Refresh FPS = ~0
```
I'll keep hacking :)

**Comment by jepler** [comment]
there's currently one debug message printed:
```
E (3255) gptimer: gptimer_start(345): timer is not enabled yet
```
it seems harmless but I didn't chase it down.

**Comment by jepler** [comment]
@ladyada please take a look if you get a chance!

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
Much testing since then with great success.

**Pull request merged**
