### PR TITLE
STM32: switch to timer allocator

### LINKED ISSUE #15: Unused variable error when compiling for NRF boards
When compiling the latest master of Protomatter in Circuitpython, there's an unused variable warning that is converted to an error by the `Werror` option:

```
In file included from ../../lib/protomatter/core.c:33:
../../lib/protomatter/arch.h: In function '_PM_convert_565_byte':
../../lib/protomatter/arch.h:1234:11: error: unused variable 'clockMask' [-Werror=unused-variable]
 1234 |   uint8_t clockMask = core->clockMask >> (core->portOffset * 8);
      |           ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by hierophect**
This PR changes the Circuitpython STM32 methods to use the new timer allocator system, allowing RGBMatrix to dynamically select out of an available pool of timers rather than being hard-coded to the TIM6 basic timer.

Also resolves #15

### CODE REVIEW

**Comment by hierophect** [comment]
I'm confused by the merge conflict. Was the Arduino code deleted? Or is the checked out code after master chronologically somehow? I don't see a develop branch.

**Comment by hierophect** [comment]
@jepler ping for your review since I don't have request permissions.

**Comment by jepler** [comment]
A substantial number of commits have been added in protomatter's main branch (still called master at this time) since the ref that was included in CircuitPython.  Visualized with `gitk origin/master...hierophect/cpy-timer-allocator`:

image

Recommendation: rebase or manually re-do on top of master
Caveat: I believe there is a build error with current Protomatter master on Python that I noted to @PaintYourDragon but did not file an issue or PR about.   One `+  delayMicroseconds(1); // Appease Teensy4` needs to be `_PM_delayMicroseconds`.

**Comment by PaintYourDragon** [comment]
Teensy delay fix is in master now. Dynamic timer usage is a desirable thing…but I suspect this will require the aforementioned manual re-do atop the current code if things have diverged that much. I’ll take a look at the scope of this.

**Comment by PaintYourDragon** [comment]
Had a look. Changes seem pretty focused in scope. This is throwing up merge conflicts?

**Comment by hierophect** [comment]
Yeah seems like they're for no reason. The resolve conflict function implies there is repeated code that isn't actually there. But I'll rebase and see if that helps.

**Comment by hierophect** [comment]
@jepler @PaintYourDragon I've fixed the issues and included the microseconds fix as well, if you'd like to take another look. As soon as this goes through, it'll enable correct CI passes on the Circuitpython PR.

**Comment by hierophect** [comment]
@jepler It's possible that #1 might be responsible for the flickering issue I've encountered using the F405 Feather on the 32x32 matrix. I'll take a closer look and see if I can't resolve it. #2 sounds like it'd mostly impact the very unlikely scenario of attempting two simultaneous protomatter instances, but I imagine having it be part of a parent structure is still probably preferable from a style perspective?

**Comment by hierophect** [comment]
resolves #15

**Comment by jepler** [comment]
@PaintYourDragon can you take a look at this?  We need to build off this ref in CircuitPython.

**Comment by PaintYourDragon** [comment]
_PM_timerFreq must match the actual timer frequency, it's used in frame rate determination and if wrong will result in a too-slow flickery matrix or an overburdened CPU.

If the frequency varies depending on which timer gets allocated, then _PM_timerFreq should be a global uint32_t rather than a \#define.

Stick with a single instance (via _PM_protoPtr) for now. Handling multiple instances just gets way WAY too ugly. The lib can handle chained panels and parallel chains, that should cover a lot of cases, but handling multiple distinct instances is opening-the-Ark-of-the-Covenant levels of bad news (Arduino mostly, due to timer interrupt handlers having to be declared at compile-time).

Other than that, looks like the merge conflicts are resolved?

**Comment by PaintYourDragon** [comment]
(It’s OK if _PM_timerFreq is a low number, as long as it matches reality. This isn’t used for clocking the data out, just for comparing the relative durations of each bitplane.)

**Comment by hierophect** [comment]
@jepler I think it would be great if we could try and bundle a fix for the flickery STM32 RGBMatrix problem alongside this addition, since I expect it's probably related to `_PM_timerFreq`. Any chance you could get your matrix set up with STM32 in the coming weeks so you could help me test? And do you happen to have a 32x32 RGBMatrix?

**Comment by PaintYourDragon** [comment]
Oh also, if _PM_timerFreq is changed to a variable…_PM_minMinPeriod will also need updating. This could still be a define, but making a reference to _PM_timerFreq, e.g.:

`#define _PM_minMinPeriod (_PM_timerFreq * 140UL / 42000000)`

_PM_minMinPeriod is the number of timer cycles (not CPU cycles) needed to shift out 32 columns of data. It’s a function of both CPU speed and timer frequency, and realistically is best determined empirically, sometimes with the help of an oscilloscope. Fortunately we already have known reasonable values from the existing code, hence the 140 and 42M in the define above (a known valid _PM_minMinPeriod for a known _PM_timerFreq), we can approximate anything else.

**Comment by jepler** [comment]
I went ahead and merged this, as it has caused multiple users issues that this was NOT merged, see https://github.com/adafruit/circuitpython/pull/3237#issuecomment-671281648

@hierophect when you have time to circle back around and fix the timer frequency issue, please do.

**Pull request merged**
